server:
    port: 8989
    contextPath: /ecommerce/api/v1
    
spring:
  
  data.rest.basePath: /ecommerce/api/v2
  
  datasource:
    url: jdbc:hsqldb:mem:testdb
    username: sa
    password:
  
  jpa:
    hibernate:
      ddl-auto: update
  